alter table CREDIT_CREDIT_APPLICATION add constraint FK_CREDIT_APPLICATION_ON_CREDIT foreign key (CREDIT_ID) references CREDIT_CREDIT(CARD_ID);
alter table CREDIT_CREDIT_APPLICATION add constraint FK_CREDIT_APPLICATION_ON_BORROWER foreign key (BORROWER_ID) references DF_INDIVIDUAL(CONTRACTOR_ID);
alter table CREDIT_CREDIT_APPLICATION add constraint FK_CREDIT_APPLICATION_ON_CARD foreign key (CARD_ID) references WF_CARD(ID) on delete CASCADE;
create index IDX_CREDIT_APPLICATION_ON_CREDIT on CREDIT_CREDIT_APPLICATION (CREDIT_ID);
create index IDX_CREDIT_APPLICATION_ON_BORROWER on CREDIT_CREDIT_APPLICATION (BORROWER_ID);
