alter table CREDIT_CREDIT add constraint FK_CREDIT_CREDIT_ON_BANK_MANAGER foreign key (BANK_MANAGER_ID) references SEC_USER(ID);
create index IDX_CREDIT_CREDIT_ON_BANK_MANAGER on CREDIT_CREDIT (BANK_MANAGER_ID);
