alter table CREDIT_CREDIT add constraint FK_CREDIT_CREDIT_ON_GUARANTOR foreign key (GUARANTOR_ID) references DF_INDIVIDUAL(CONTRACTOR_ID);
create index IDX_CREDIT_CREDIT_ON_GUARANTOR on CREDIT_CREDIT (GUARANTOR_ID);
