-- begin CREDIT_CREDIT
alter table CREDIT_CREDIT add constraint FK_CREDIT_CREDIT_ON_BANK_MANAGER foreign key (BANK_MANAGER_ID) references SEC_USER(ID)^
alter table CREDIT_CREDIT add constraint FK_CREDIT_CREDIT_ON_CREDI_KIND foreign key (CREDI_KIND_ID) references CREDIT_CREDIT_KIND(ID)^
alter table CREDIT_CREDIT add constraint FK_CREDIT_CREDIT_ON_BANK foreign key (BANK_ID) references DF_BANK(ID)^
alter table CREDIT_CREDIT add constraint FK_CREDIT_CREDIT_ON_GUARANTOR foreign key (GUARANTOR_ID) references DF_INDIVIDUAL(CONTRACTOR_ID)^
alter table CREDIT_CREDIT add constraint FK_CREDIT_CREDIT_ON_CARD foreign key (CARD_ID) references WF_CARD(ID) on delete CASCADE^
create index IDX_CREDIT_CREDIT_ON_BANK_MANAGER on CREDIT_CREDIT (BANK_MANAGER_ID)^
create index IDX_CREDIT_CREDIT_ON_CREDI_KIND on CREDIT_CREDIT (CREDI_KIND_ID)^
create index IDX_CREDIT_CREDIT_ON_BANK on CREDIT_CREDIT (BANK_ID)^
create index IDX_CREDIT_CREDIT_ON_GUARANTOR on CREDIT_CREDIT (GUARANTOR_ID)^
-- end CREDIT_CREDIT
-- begin CREDIT_CREDIT_APPLICATION
alter table CREDIT_CREDIT_APPLICATION add constraint FK_CREDIT_APPLICATION_ON_CREDIT foreign key (CREDIT_ID) references CREDIT_CREDIT(CARD_ID)^
alter table CREDIT_CREDIT_APPLICATION add constraint FK_CREDIT_APPLICATION_ON_BORROWER foreign key (BORROWER_ID) references DF_CONTRACTOR(CORRESPONDENT_ID)^
alter table CREDIT_CREDIT_APPLICATION add constraint FK_CREDIT_APPLICATION_ON_CARD foreign key (CARD_ID) references WF_CARD(ID) on delete CASCADE^
create index IDX_CREDIT_APPLICATION_ON_CREDIT on CREDIT_CREDIT_APPLICATION (CREDIT_ID)^
create index IDX_CREDIT_APPLICATION_ON_BORROWER on CREDIT_CREDIT_APPLICATION (BORROWER_ID)^
-- end CREDIT_CREDIT_APPLICATION
-- begin TM_TASK
alter table TM_TASK add constraint FK_TM_TASK_ON_CREDIT_APPLICATION foreign key (CREDIT_APPLICATION_ID) references CREDIT_CREDIT_APPLICATION(CARD_ID)^
create index IDX_TM_TASK_ON_CREDIT_APPLICATION on TM_TASK (CREDIT_APPLICATION_ID)^
-- end TM_TASK
